In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df=pd.read_csv('client_data.csv')

In [4]:
df.head(10)

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,forecast_price_pow_off_peak,has_gas,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,origin_up,pow_max,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,0,0.0,1.78,0.114481,0.098142,40.606701,t,0.00,25.44,25.44,2,678.99,3,lxidpiddsbxsbosboudacockeimpuepw,43.648,1
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,0.0,16.27,0.145711,0.000000,44.311378,f,0.00,16.38,16.38,1,18.89,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.800,0
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,0,0.0,38.72,0.165794,0.087899,44.311378,f,0.00,28.60,28.60,1,6.60,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.856,0
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,0,0.0,19.83,0.146694,0.000000,44.311378,f,0.00,30.22,30.22,1,25.46,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.200,0
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,526,0.0,131.73,0.116900,0.100015,40.606701,f,52.32,44.91,44.91,1,47.98,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,19.800,0
5,1aa498825382410b098937d65c4ec26d,usilxuppasemubllopkaafesmlibmsdf,8302,0,1998,2011-12-09,2016-12-09,2015-11-01,2015-12-10,796.94,1998,0.0,30.12,0.164775,0.086131,45.308378,f,181.21,33.12,33.12,1,118.89,4,lxidpiddsbxsbosboudacockeimpuepw,13.200,1
6,7ab4bf4878d8f7661dfc20e9b8e18011,foosdfpfkusacimwkcsosbicdxkicaua,45097,0,0,2011-12-02,2016-12-02,2011-12-02,2015-12-03,8069.28,0,0.0,0.00,0.166178,0.087538,44.311378,f,0.00,4.04,4.04,1,346.63,4,lxidpiddsbxsbosboudacockeimpuepw,15.000,1
7,01495c955be7ec5e7f3203406785aae0,foosdfpfkusacimwkcsosbicdxkicaua,29552,0,1260,2010-04-21,2016-04-21,2010-04-21,2015-04-22,864.73,751,0.0,144.49,0.115174,0.098837,40.606701,f,70.63,53.92,53.92,1,100.09,6,lxidpiddsbxsbosboudacockeimpuepw,26.400,0
8,f53a254b1115634330c12c7fdbf7958a,usilxuppasemubllopkaafesmlibmsdf,2962,0,0,2011-09-23,2016-09-23,2011-09-23,2015-09-25,444.38,0,0.0,15.85,0.145711,0.000000,44.311378,f,0.00,12.82,12.82,1,42.59,4,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.200,0
9,10c1b2f97a2d2a6f10299dc213d1a370,lmkebamcaaclubfxadlmueccxoimlema,26064,0,2188,2010-05-04,2016-05-04,2015-04-29,2015-05-05,2738.10,2188,0.0,130.43,0.115761,0.099419,40.606701,f,219.59,33.42,33.42,1,329.60,6,lxidpiddsbxsbosboudacockeimpuepw,31.500,0

In [5]:
price_data = pd.read_csv('price_data.csv')
price_data.head(10)

,id,price_date,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
0,038af19179925da21a25619c5a24b745,2015-01-01,0.151367,0.0,0.0,44.266931,0.0,0.0
1,038af19179925da21a25619c5a24b745,2015-02-01,0.151367,0.0,0.0,44.266931,0.0,0.0
2,038af19179925da21a25619c5a24b745,2015-03-01,0.151367,0.0,0.0,44.266931,0.0,0.0
3,038af19179925da21a25619c5a24b745,2015-04-01,0.149626,0.0,0.0,44.266931,0.0,0.0
4,038af19179925da21a25619c5a24b745,2015-05-01,0.149626,0.0,0.0,44.266931,0.0,0.0
5,038af19179925da21a25619c5a24b745,2015-06-01,0.149626,0.0,0.0,44.266930,0.0,0.0
6,038af19179925da21a25619c5a24b745,2015-07-01,0.150321,0.0,0.0,44.444710,0.0,0.0
7,038af19179925da21a25619c5a24b745,2015-08-01,0.145859,0.0,0.0,44.444710,0.0,0.0
8,038af19179925da21a25619c5a24b745,2015-09-01,0.145859,0.0,0.0,44.444710,0.0,0.0
9,038af19179925da21a25619c5a24b745,2015-10-01,0.145859,0.0,0.0,44.444710,0.0,0.0

In [6]:
df.shape

(14606, 26)

In [7]:
price_data.shape

(193002, 8)

In [8]:
df.sample(10)

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,forecast_price_pow_off_peak,has_gas,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,origin_up,pow_max,churn
11602,142ca0520a4fcb5414d4668f51d8d9ed,ewpakwlliwisiwduibdlfmalxowmwpci,16851,0,4368,2012-05-11,2016-05-11,2012-05-11,2015-05-14,1525.63,4368,0.0,17.00,0.163479,0.086225,44.311378,f,403.78,22.95,22.95,1,144.01,4,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.856,0
13136,e967793f2aef0aea1a1cd5dc33342d66,usilxuppasemubllopkaafesmlibmsdf,1797,0,0,2011-06-09,2016-06-09,2011-06-09,2015-06-14,269.49,0,0.0,6.92,0.145711,0.000000,44.311378,f,0.00,16.84,16.84,1,32.19,5,kamkkxfxxuwbdslkwifmmcsiusiuosws,10.350,0
7177,cc722b8e71bde985f6d607658c0e1595,usilxuppasemubllopkaafesmlibmsdf,31213,0,2498,2011-12-07,2016-12-07,2015-05-24,2015-12-08,3403.78,2498,0.0,132.92,0.116509,0.101397,40.606701,f,259.09,1.44,1.44,1,417.19,4,kamkkxfxxuwbdslkwifmmcsiusiuosws,33.000,0
8706,c0b919c3041be3bc34fa30419b234486,foosdfpfkusacimwkcsosbicdxkicaua,23125,0,1948,2011-02-02,2016-02-02,2015-02-05,2015-02-03,2346.15,1948,0.0,130.32,0.118066,0.101176,40.606701,f,193.22,25.92,25.92,1,289.59,5,lxidpiddsbxsbosboudacockeimpuepw,17.321,0
6623,bc3ef7a4ada733ffbb77b8f38e23ed61,foosdfpfkusacimwkcsosbicdxkicaua,7072,0,0,2009-07-24,2016-07-24,2009-07-24,2015-07-27,1050.59,0,0.0,16.39,0.144902,0.000000,44.311378,f,0.00,18.62,18.62,1,99.04,7,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.200,0
6333,fd3144c3dcb36805c71a6e50add44434,usilxuppasemubllopkaafesmlibmsdf,44176,0,4500,2010-01-30,2016-12-06,2015-11-18,2015-12-07,4368.13,4500,0.0,145.83,0.111195,0.096077,40.606701,f,414.64,1.20,1.20,1,392.06,6,lxidpiddsbxsbosboudacockeimpuepw,26.400,0
6142,f7d127623a8a701baae595b4e1b8623d,foosdfpfkusacimwkcsosbicdxkicaua,49466,0,7260,2011-08-11,2016-12-02,2014-12-02,2015-12-03,722.31,814,0.0,130.42,0.115237,0.100123,40.939027,f,79.87,17.12,17.12,1,84.51,4,lxidpiddsbxsbosboudacockeimpuepw,16.400,0
10152,0b81e05fd0c98d41367645f1dd7a29a9,usilxuppasemubllopkaafesmlibmsdf,47371,0,284,2011-11-03,2016-11-03,2014-06-27,2015-11-05,887.44,0,0.0,62.19,0.147506,0.000000,45.308378,f,0.00,16.92,16.92,1,87.32,4,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.200,0
7775,6d693bac4c5ed5298773ee9cbb51980b,foosdfpfkusacimwkcsosbicdxkicaua,210449,356870,18209,2012-12-13,2016-05-13,2015-05-24,2014-12-31,2735.29,2626,0.0,130.29,0.111125,0.094787,40.606701,t,242.69,24.18,24.18,2,289.40,3,lxidpiddsbxsbosboudacockeimpuepw,20.000,0
7299,db8b5b3e8c24e99fc2e8b0cfd414795c,lmkebamcaaclubfxadlmueccxoimlema,1599694,0,208086,2010-06-24,2016-06-24,2010-06-24,2015-06-26,4307.93,4584,0.0,132.55,0.115174,0.098837,40.606701,f,432.11,14.92,14.92,8,536.36,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,16.224,0

In [9]:
###Descriptive statistics of data
"Data types
It is useful to first understand the data that you're dealing with along with the data types of each column. The data types may dictate how you transform and engineer features.

To get an overview of the data types within a data frame, use the info() method."

SyntaxError: unterminated string literal (detected at line 2) (1712700764.py, line 2)

In [ ]:
df.info()

In [ ]:
### Statistics

Now let's look at some statistics about the datasets. We can do this by using the `describe()` method.

In [ ]:
df.describe().T

In [ ]:
df.isnull().sum()

In [ ]:
df.isna().sum()

In [ ]:
df.date_activ = pd.to_datetime(df.date_activ)
df.date_activ

In [ ]:
df.date_end = pd.to_datetime(df.date_end)
df.date_end

In [ ]:
df.date_modif_prod = pd.to_datetime(df.date_modif_prod)
df.date_renewal = pd.to_datetime(df.date_renewal)

In [ ]:
df.info()

In [ ]:
numerical_col = [i for i in df.columns if df[i].dtype == 'float64' or df[i].dtype == 'int64']

 
categorical_col = [i for i in df.columns if df[i].dtype =='O']

In [ ]:
len(numerical_col) , len(categorical_col)

In [ ]:
categorical_col

In [ ]:
numerical_col

In [ ]:
df.origin_up.value_counts()

In [ ]:
'''Exploratory Analysis'''

In [ ]:
## Data visualization

If you're working in Python, two of the most popular packages for visualization are `matplotlib` and `seaborn`. We highly recommend you use these, or at least be familiar with them because they are ubiquitous!

Below are some functions that you can use to get started with visualizations.

In [ ]:
print(df.columns)

print()

print("Total number of columns : ",len(df.columns))

In [ ]:
'''Univariate Analysis'''

'''Categorical Data'''

In [ ]:
nominal_data = [i for i in df[categorical_col] if df[i].nunique()<10]

nominal_data

In [ ]:
'''Column: channel_sales'''

In [ ]:
df[['channel_sales']].head()

In [ ]:
df.channel_sales.unique()

In [ ]:
df.channel_sales.value_counts()

In [ ]:
print(f'Total No. of uniue categories: {df.channel_sales.nunique()}')

In [ ]:
df.channel_sales.value_counts().plot(kind='pie' , autopct='%1.2f')

In [ ]:
df.channel_sales.value_counts().plot(kind='bar')

In [ ]:
df.channel_sales.describe(include='all')

In [ ]:
df.has_gas.value_counts()

In [ ]:
df.has_gas.value_counts().plot(kind='bar')

In [ ]:
df[['origin_up']].head()

In [ ]:
df.origin_up.value_counts()

In [ ]:
df.origin_up.value_counts().plot(kind='bar')

In [ ]:
'''Numerical Analysis'''

In [ ]:
df[['cons_12m','cons_gas_12m','cons_last_month','forecast_cons_12m','forecast_cons_year',
    'forecast_discount_energy']].hist(figsize=(12, 8), bins=20)
plt.show()

In [ ]:
df[['forecast_meter_rent_12m','forecast_price_energy_off_peak',  'forecast_price_energy_peak', 'forecast_price_pow_off_peak',
    'imp_cons','margin_gross_pow_ele',]].hist(figsize=(12, 8), bins=20)
plt.show()

In [ ]:
df[['margin_net_pow_ele','nb_prod_act','net_margin','num_years_antig','pow_max','churn']].hist(figsize=(12, 8), bins=20)
plt.show()

In [ ]:
sns.kdeplot(data=df.forecast_price_energy_peak, fill=True, common_norm=False, palette='husl')
plt.show()

In [ ]:
sns.kdeplot(data=df.forecast_meter_rent_12m, fill=True, common_norm=False, palette='husl')
plt.show()

In [ ]:
sns.kdeplot(data=df.num_years_antig, fill=True, common_norm=False, palette='husl')
plt.show()

In [ ]:
df.net_margin.plot(kind='kde')

'''Bivariate Analysis'''

'''Categorical columns'''

In [ ]:
categorical_col

In [ ]:
plt.figure(figsize=(10, 6))
sns.barplot(x='Category', y='Value', hue='Label', data=df, palette='viridis')

In [ ]:
cross_tab1 = pd.crosstab(df['channel_sales'], df['has_gas'])
cross_tab1

In [ ]:
cross_tab2 = pd.crosstab(df['channel_sales'], df['origin_up'])
cross_tab2

In [ ]:
from scipy.stats import chi2_contingency

contingency_table = pd.crosstab(df['channel_sales'], df['has_gas'])
chi2, p, _, _ = chi2_contingency(contingency_table)
print(f"Chi-square: {chi2}\nP-value: {p}")
#statistical sign(p<0.05)

In [ ]:
from scipy.stats import chi2_contingency

contingency_table = pd.crosstab(df['channel_sales'], df['origin_up'])
chi2, p, _, _ = chi2_contingency(contingency_table)
print(f"Chi-square: {chi2}\nP-value: {p}")

In [ ]:
from scipy.stats import chi2_contingency

contingency_table = pd.crosstab(df['has_gas'], df['origin_up'])
chi2, p, _, _ = chi2_contingency(contingency_table)
print(f"Chi-square: {chi2}\nP-value: {p}")
#no statistica sig(p  nhigh val)

In [ ]:
'''Numerical Analysis'''

In [ ]:
correlation = df['forecast_price_energy_peak'].corr(df['churn'])
print(f"Correlation coefficient: {correlation}")

In [ ]:
correlation = df['cons_12m'].corr(df['churn'])
print(f"Correlation coefficient: {correlation}")

In [ ]:
correlation = df['cons_gas_12m'].corr(df['churn'])
print(f"Correlation coefficient: {correlation}")

In [ ]:
correlation = df['cons_last_month'].corr(df['churn'])
print(f"Correlation coefficient: {correlation}")

In [ ]:
correlation = df['pow_max'].corr(df['churn'])
print(f"Correlation coefficient: {correlation}")

In [ ]:
import statsmodels.api as sm
X = sm.add_constant(df['margin_gross_pow_ele'])
model = sm.OLS(df['churn'], X).fit()
print(model.summary())

In [ ]:
import statsmodels.api as sm
X = sm.add_constant(df['cons_last_month'])
model = sm.OLS(df['churn'], X).fit()
print(model.summary())

In [ ]:
import seaborn as sns
correlation_matrix = df[['cons_12m','cons_gas_12m', 'cons_last_month','forecast_cons_12m', 
'forecast_cons_year', 'forecast_discount_energy','forecast_meter_rent_12m','churn']].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.show()

In [ ]:

correlation_matrix = df[['forecast_meter_rent_12m','forecast_price_energy_off_peak','forecast_price_energy_peak', 
                     'forecast_price_pow_off_peak','imp_cons','margin_gross_pow_ele']].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.show()

In [ ]:
correlation_matrix = df[['margin_net_pow_ele','nb_prod_act','net_margin','num_years_antig','pow_max','churn']].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.show()

In [ ]:
sns.pairplot(df[['cons_12m','cons_gas_12m','cons_last_month','forecast_cons_12m','forecast_cons_year',
    'forecast_discount_energy']])
plt.show()

In [ ]:
sns.pairplot(df[['forecast_meter_rent_12m','forecast_price_energy_off_peak',  'forecast_price_energy_peak', 'forecast_price_pow_off_peak',
    'imp_cons','margin_gross_pow_ele',]])
plt.show()

In [ ]:
sns.pairplot(df[['margin_net_pow_ele','nb_prod_act','net_margin','num_years_antig','pow_max','churn']])
plt.show()

In [ ]:
import statsmodels.api as sm
from statsmodels.graphics.factorplots import interaction_plot

# Example interaction plot
interaction_plot(x=df['forecast_discount_energy'], trace=df[ 'has_gas'], response=df['churn'])
plt.show()